name: Release Extension

on:
  push:
    tags:
      - "v*.*.*"   # Trigger on version tags like v0.1.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install vsce
        run: npm i -g @vscode/vsce

      - name: Install dependencies
        run: npm ci || npm i

      - name: Compile extension
        run: npm run compile

      - name: Package extension
        run: vsce package

      - name: Publish to VS Code Marketplace
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: vsce publish -p "$VSCE_TOKEN"

      - name: Save VSIX filename
        id: vsix
        run: |
          file=$(ls -1 *.vsix | tail -n 1)
          echo "file=$file" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and upload VSIX
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            See CHANGELOG.md for details.
          files: |
            ${{ steps.vsix.outputs.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}